### ISSUE TITLE
Compile error with beam-core 0.8.0.0 

### ISSUE THREAD

**Issue by AlijahSmith** [tathougies/beam-mysql#11]
Database.Beam.Backend.Types.FromBackendRowF has been changed and moved to Database.Beam.Backend.SQL.Row.FromBackendRowF in beam-core 0.8. 

```
   [project]/.stack-work/downloaded/V7BgOCksndS0/Database/Beam/MySQL/Connection.hs:138:23: error:
        Not in scope: data constructor ‘PeekField’
        Perhaps you meant variable ‘peekField’ (imported from Database.Beam.Backend)
        |
    138 |                 step (PeekField next) curCol fields@((desc, field):_) =
        |                       ^^^^^^^^^

    [project]/.stack-work/downloaded/V7BgOCksndS0/Database/Beam/MySQL/Connection.hs:143:23: error:
        Not in scope: data constructor ‘PeekField’
        Perhaps you meant variable ‘peekField’ (imported from Database.Beam.Backend)
        |
    143 |                 step (PeekField next) curCol [] =
        |                       ^^^^^^^^^

   [project]/.stack-work/downloaded/V7BgOCksndS0/Database/Beam/MySQL/Connection.hs:145:23: error:
        Not in scope: data constructor ‘CheckNextNNull’
        |
    145 |                 step (CheckNextNNull n next) curCol fields
        |                       ^^^^^^^^^^^^^^


```

**Comment by ohad** [comment]
Workaround for me in `stack.yaml`:
```
resolver: lts-13.6
```
and
```
packages:
- .
- location:
    git: https://github.com/tathougies/beam.git
    commit: b245bf2c0b4c810dbac334d08ca572cec49e4d83
  extra-dep: true
  subdirs:
    - beam-core
- location:
    git: https://github.com/tathougies/beam-mysql
    commit: 2c561b486acf80c7847f48667f1a7d9222f2b35a
  extra-dep: true
```
